### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by e3rd** [fjueic/gsconnect-mount-manager#2]
Nothing appears in Nautilus when I click Mount. If you're not planning to do the Ubuntu support, feel free to close this.

```
2023-12-14T13:36:58.812567+01:00 mycomputer gjs[2188]: JS ERROR: my_samsung A40: Gio.IOErrorEnum: Connection failed#012_handleMount/</<@/home/jsmith/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:257:38#012@/home/jsmith/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:731:17
2023-12-14T13:38:27.092475+01:00 mycomputer gjs[2188]: message repeated 4 times: [ JS ERROR: my_samsung A40: Gio.IOErrorEnum: Connection failed#012_handleMount/</<@/home/jsmith/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:257:38#012@/home/jsmith/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:731:17]
```

**Comment by fjueic** [comment]
@e3rd dumb question: did you log out and log in?

i didn't test this on ubuntu
i will check this. downloading iso rn

**Comment by e3rd** [comment]
Not at all dumb, I didn't bother before. It appeared in the Nautilus, now! However, when I try to click:

![image](https://github.com/fjueic/gsconnect-mount-manager/assets/6942231/964fb712-72d9-4fc8-8532-a5d53b1b6a4f)

![image](https://github.com/fjueic/gsconnect-mount-manager/assets/6942231/1bd2a7ad-1668-4c7d-8195-4cf4898edb2e)

No log in syslog.

If I access in a terminal
~/.gsconnectMounts/Jarý Ksukol A40___eb248103_75c5_4050_903a_7db2333e09b0

it symlinks me deeper and deeper

~/.gsconnectMounts/Jarý Ksukol A40___eb248103_75c5_4050_903a_7db2333e09b0/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/Internal storage/

(Don't bother downloading iso just because of me.)

**Comment by fjueic** [comment]
@e3rd this is supposed to be a symbolic link and its intended behavior
It points to itself please don't try to access using terminal
there is a service supposed to be running in the background, when you open a symbolic link using Nautilus it will open the new session of Nautilus with appropriate mapped location

**Comment by fjueic** [comment]
@e3rd can you see your device ip mounted on side panel of Nautilus
clicking it shows this error
![image](https://github.com/fjueic/gsconnect-mount-manager/assets/89282645/1b96442a-2b34-4dd2-a28b-a42fac9888b4)

**Comment by e3rd** [comment]
Service seems to be running

```
$ systemctl --user status gsconnect-mount-manager.service
● gsconnect-mount-manager.service - GSConnect Mount Manager
     Loaded: loaded (/etc/xdg/systemd/user/gsconnect-mount-manager.service; enabled; preset: enabled)
     Active: active (running) since Thu 2023-12-14 14:31:13 CET; 24min ago
   Main PID: 24642 (python3)
      Tasks: 1 (limit: 37672)
     Memory: 9.1M
        CPU: 263ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/gsconnect-mount-manager.service
             └─24642 python3 /home/jsmith/.config/gsconnect-mount-manager/run.py

pro 14 14:31:13 kolonok systemd[1670]: Started gsconnect-mount-manager.service - GSConnect Mount Manager.
$ journalctl -u gsconnect-mount-manager.service 
-- No entries --
$ 

```


I see no IP at the side panel

![image](https://github.com/fjueic/gsconnect-mount-manager/assets/6942231/6931e2ea-6b74-4fc9-b04a-ed6a6aa74bad)

**Comment by fjueic** [comment]
you most probably don't have sshfs
this project tries to solve permission error and don't handle any kind of mounting
GSconnect ignores paths being sent by android device
if this you can't see your device IP mounted("/") in Nautilus thats an issue you should look for in gsconnect repo

i tried in wm but the device was not showing up
i will try in live environment tomorrow

**Comment by e3rd** [comment]
Thanks, I didn't know! As I can't see the IP, it's clearly a broader gsconnect problem.

```
$ whereis sshfs
sshfs: /usr/bin/sshfs /usr/share/man/man1/sshfs.1.gz
$ sshfs
missing host
see `sshfs -h' for usage 
```
